DROP DATABASE IF EXISTS `<SCHEMA_NAME>`;

CREATE DATABASE IF NOT EXISTS `<SCHEMA_NAME>` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `<SCHEMA_NAME>`;

CREATE TABLE IF NOT EXISTS `response` (
	RESPONSE_ID int unsigned NOT NULL AUTO_INCREMENT,
    TLD varchar(255) NOT NULL,
    REQUEST_URI varchar(1023) NOT NULL,
    RESPONSE_HTTP_STATUS int NOT NULL,
    RESPONSE_HEADERS longtext NULL,
    RESPONSE_BODY longtext NULL,    
    PRIMARY KEY(RESPONSE_ID),
    UNIQUE KEY `tld` (TLD)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
